<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            [
                'id_soal' => 'ADNK01',
                'question_text' => 'Pada waktu belajar untuk Penilaian atau Ulangan Harian,Penilaian tengah semester dan Penilaian akhir semester apakah anda memilih :',
                'id_option_a' => 1,
                'option_a' => 'membaca catatan, membaca judul dan sub-judul dalam buku, dan melihat diagram dan ilustrasi',
                'id_option_b' => 2,
                'option_b' => 'meminta seseorang memberi anda pertanyaan, atau menghafal dalam hati sendirian',
                'id_option_c' => 3,
                'option_c' => 'membuat catatan pada kartu dan membuat model atau diagram',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK02',
                'question_text' => 'Apa yang kalian lakukan sewaktu anda mendengarkan musik?',
                'id_option_a' => 1,
                'option_a' => 'berkhayal melihat benda-benda yang sesuai dengan musik yang sedang didengarkan',
                'id_option_b' => 2,
                'option_b' => 'berdendang mengikuti alunan musik tersebut',
                'id_option_c' => 3,
                'option_c' => 'bergerak mengikuti musik tersebut, mengetukkan kaki mengikuti irama, dsb.',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK03',
                'question_text' => 'Pada waktu kalian sedang memecahkan masalah,apakah anda :',
                'id_option_a' => 1,
                'option_a' => 'membuat daftar, mengatur langkah, dan mengeceknya setelah langkah itu dikerjakan',
                'id_option_b' => 2,
                'option_b' => 'menelpon teman atau ahli untuk membicarakan masalah tersebut',
                'id_option_c' => 3,
                'option_c' => 'menguraikan (menganalisa) masalah itu atau melakukan semua langkah yang anda pikirkan',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK04',
                'question_text' => 'Jika kalian membaca untuk sekedar hiburan ,apakah kalian memilih:',
                'id_option_a' => 1,
                'option_a' => 'buku perjalanan dengan banyak gambar di dalamnya',
                'id_option_b' => 2,
                'option_b' => 'cerita misteri yang penuh dengan percakapan di dalamnya',
                'id_option_c' => 3,
                'option_c' => 'buku yang dapat menjawab pertanyaan dan memecahkan masalah anda',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK05',
                'question_text' => 'Untuk mempelajari bagaimana kerja komputer,apakah anda memilih :',
                'id_option_a' => 1,
                'option_a' => 'menonton film tentang cara kerja computer',
                'id_option_b' => 2,
                'option_b' => 'mendengarkan seseorang menjelaskan cara keja computer',
                'id_option_c' => 3,
                'option_c' => 'membongkar komputer dan mencoba menemukan sendiri cara kerjanya',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK06',
                'question_text' => 'Anda baru saja memasuki museum ilmu pengetahuan,seperti taman pintar,Tekno park,dll apa yang anda lakukan pertama kali?',
                'id_option_a' => 1,
                'option_a' => 'melihat sekeliling dan menemukan peta yang menunjukkan lokasi berbagai benda yang dipamerkan',
                'id_option_b' => 2,
                'option_b' => 'berbicara dengan penjaga museum dan bertanya kepadanya tentang benda-benda yang dipamerkan',
                'id_option_c' => 3,
                'option_c' => 'melihat pada benda pertama yang kelihatan menarik, dan baru kemudian membaca petunjuk lokasi benda-benda lainnya',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK07',
                'question_text' => 'Jenis restoran atau rumah makan apa yang anda tidak sukai?',
                'id_option_a' => 1,
                'option_a' => 'restoran yang lampunya terlalu terang',
                'id_option_b' => 2,
                'option_b' => 'restoran yang musiknya terlalu keras',
                'id_option_c' => 3,
                'option_c' => 'restoran yang kursinya tidak nyaman',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK08',
                'question_text' => 'Apa kira – kira yang anda lakukan pada waktu kalian merasa senang?',
                'id_option_a' => 1,
                'option_a' => 'meringis (tersenyum)',
                'id_option_b' => 2,
                'option_b' => 'berteriak dengan senang',
                'id_option_c' => 3,
                'option_c' => 'melompat dengan senang',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK09',
                'question_text' => 'Seandainya anda berada pada suatu acara pesta,entah pernikahan atau yang lainnya,apa yang akan kira – kira paling anda ingat pada keesokan harinya?',
                'id_option_a' => 1,
                'option_a' => 'muka orang-orang dalam pesta, tetapi bukan namanya',
                'id_option_b' => 2,
                'option_b' => 'nama orang-orang dalam pesta, tetapi bukan mukanya',
                'id_option_c' => 3,
                'option_c' => 'sesuatu yang anda lakukan dan katakan selama dalam pesta',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK10',
                'question_text' => 'Pada waktu kalian bercerita,apakan anda memilih untuk:',
                'id_option_a' => 1,
                'option_a' => 'menulisnya',
                'id_option_b' => 2,
                'option_b' => 'menceritakannya dengan suara keras',
                'id_option_c' => 3,
                'option_c' => 'memerankannya',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK11',
                'question_text' => 'Apa yang paling mengganggu bagi kalian pada waktu anda mencoba untuk berkonsentrasi?',
                'id_option_a' => 1,
                'option_a' => 'gangguan visual',
                'id_option_b' => 2,
                'option_b' => 'suara gaduh',
                'id_option_c' => 3,
                'option_c' => 'gangguan lainnya seperti rasa lapar, sepatu yang sempit, atau rasa khawatir',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK12',
                'question_text' => 'Apa yang kira – kira anda lakukan ketika kalian sedang marah?',
                'id_option_a' => 1,
                'option_a' => 'cemberut atau memperlihatkan muka marah',
                'id_option_b' => 2,
                'option_b' => 'berteriak atau “mengamuk”',
                'id_option_c' => 3,
                'option_c' => 'menghentakkan kaki dengan keras dan membanting pintu',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK13',
                'question_text' => 'Apa yang kira – kira kalian lakukan ,jika anda sedang antre untuk menonton Bioskop?',
                'id_option_a' => 1,
                'option_a' => 'melihat-lihat pada poster iklan film lainnya',
                'id_option_b' => 2,
                'option_b' => 'berbicara dengan orang di sebelah anda',
                'id_option_c' => 3,
                'option_c' => 'mengetukkan kaki atau berjalan ke arah lain',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK14',
                'question_text' => 'Apakah anda lebih suka mengikuti :',
                'id_option_a' => 1,
                'option_a' => 'kelas melukis',
                'id_option_b' => 2,
                'option_b' => 'kelas music',
                'id_option_c' => 3,
                'option_c' => 'kelas olah raga',
                'category' => 'A',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK15',
                'question_text' => 'Pada waktu belajar untuk tes, apakah anda memilih' ,
                'id_option_a' => 1,
                'option_a' => 'membaca catatan, membaca judul dan sub-judul dalam buku, dan melihat diagram dan ilustrasi',
                'id_option_b' => 2,
                'option_b' => 'meminta seseorang memberi anda pertanyaan, atau menghafal dalam hati sendirian',
                'id_option_c' => 3,
                'option_c' => 'membuat catatan pada kartu dan membuat model atau diagram',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK16',
                'question_text' => 'Apa yang anda lakukan pada waktu mendengarkan musik?' ,
                'id_option_a' => 1,
                'option_a' => 'berkhayal (melihat benda-benda yang sesuai dengan musik yang sedang didengarkan)',
                'id_option_b' => 2,
                'option_b' => 'berdendang mengikuti alunan musik tersebut',
                'id_option_c' => 3,
                'option_c' => 'bergerak mengikuti musik tersebut, mengetukkan kaki mengikuti irama, dsb',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK17',
                'question_text' => 'Pada waktu anda memecahkan masalah, apakah anda' ,
                'id_option_a' => 1,
                'option_a' => 'membuat daftar, mengatur langkah, dan mengeceknya setelah langkah itu dikerjakan',
                'id_option_b' => 2,
                'option_b' => 'menelpon teman atau ahli untuk membicarakan masalah tersebut',
                'id_option_c' => 3,
                'option_c' => 'menguraikan (menganalisa) masalah itu atau melakukan semua langkah yang anda pikirkan',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK18',
                'question_text' => 'Jika anda ingin membaca untuk hiburan, apakah anda memilih' ,
                'id_option_a' => 1,
                'option_a' => 'buku perjalanan dengan banyak gambar di dalamnya',
                'id_option_b' => 2,
                'option_b' => 'cerita misteri yang penuh dengan percakapan di dalamnya',
                'id_option_c' => 3,
                'option_c' => 'buku yang dapat menjawab pertanyaan dan memecahkan masalah anda',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK19',
                'question_text' => 'Untuk mempelajari bagaimana cara kerja komputer, apakah anda memilih' ,
                'id_option_a' => 1,
                'option_a' => 'menonton film tentang cara kerja computer',
                'id_option_b' => 2,
                'option_b' => 'mendengarkan seseorang menjelaskan cara keja computer',
                'id_option_c' => 3,
                'option_c' => 'membongkar komputer dan mencoba menemukan sendiri cara kerjanya',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK20',
                'question_text' => 'Anda baru saja memasuki museum ilmu pengetahuan, apa yang anda lakukan pertama kali?' ,
                'id_option_a' => 1,
                'option_a' => 'melihat sekeliling dan menemukan peta yang menunjukkan lokasi berbagai benda yang dipamerkan',
                'id_option_b' => 2,
                'option_b' => 'berbicara dengan penjaga museum dan bertanya kepadanya tentang benda-benda yang dipamerkan',
                'id_option_c' => 3,
                'option_c' => 'melihat pada benda pertama yang kelihatan menarik, dan baru kemudian membaca petunjuk lokasi benda-benda lainnya',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK21',
                'question_text' => 'Jenis restoran apa yang tidak anda sukai?' ,
                'id_option_a' => 1,
                'option_a' => 'restoran yang lampunya terlalu terang',
                'id_option_b' => 2,
                'option_b' => 'restoran yang musiknya terlalu keras',
                'id_option_c' => 3,
                'option_c' => 'restoran yang kursinya tidak nyaman',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK22',
                'question_text' => 'Apakah anda lebih suka mengikuti' ,
                'id_option_a' => 1,
                'option_a' => 'kelas melukis',
                'id_option_b' => 2,
                'option_b' => 'kelas music',
                'id_option_c' => 3,
                'option_c' => 'kelas olah raga',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK23',
                'question_text' => 'Apa yang kira-kira anda lakukan pada waktu anda merasa senang?' ,
                'id_option_a' => 1,
                'option_a' => 'meringis (tersenyum)',
                'id_option_b' => 2,
                'option_b' => 'berteriak dengan senang',
                'id_option_c' => 3,
                'option_c' => 'melompat dengan senang',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK24',
                'question_text' => 'Seandainya anda berada pada suatu pesta, apa yang kira-kira akan paling anda ingat pada keesokan harinya?' ,
                'id_option_a' => 1,
                'option_a' => 'muka orang-orang dalam pesta, tetapi bukan namanya',
                'id_option_b' => 2,
                'option_b' => 'nama orang-orang dalam pesta, tetapi bukan mukanya',
                'id_option_c' => 3,
                'option_c' => 'sesuatu yang anda lakukan dan katakan selama dalam pesta',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK25',
                'question_text' => 'Pada waktu anda bercerita, apakah anda memilih untuk' ,
                'id_option_a' => 1,
                'option_a' => 'menulisnya',
                'id_option_b' => 2,
                'option_b' => 'menceritakannya dengan suara keras',
                'id_option_c' => 3,
                'option_c' => 'memerankannya',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK26',
                'question_text' => 'Apa yang paling mengganggu bagi anda pada waktu anda mencoba untuk berkonsentrasi?' ,
                'id_option_a' => 1,
                'option_a' => 'gangguan visual',
                'id_option_b' => 2,
                'option_b' => 'suara gaduh',
                'id_option_c' => 3,
                'option_c' => 'gangguan lainnya seperti rasa lapar, sepatu yang sempit, atau rasa khawatir',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK27',
                'question_text' => 'Apa yang kira-kira anda lakukan pada waktu anda marah?' ,
                'id_option_a' => 1,
                'option_a' => 'cemberut atau memperlihatkan muka marah',
                'id_option_b' => 2,
                'option_b' => 'berteriak atau “mengamuk”',
                'id_option_c' => 3,
                'option_c' => 'menghentakkan kaki dengan keras dan membanting pintu',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK28',
                'question_text' => 'Apa yang kira-kira akan anda lakukan pada waktu berdiri menunggu antrian di gedung bioskop?' ,
                'id_option_a' => 1,
                'option_a' => 'melihat-lihat pada poster iklan film lainnya',
                'id_option_b' => 2,
                'option_b' => 'berbicara dengan orang di sebelah anda',
                'id_option_c' => 3,
                'option_c' => 'mengetukkan kaki atau berjalan ke arah lain',
                'category' => 'B',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK29',
                'question_text' => 'Ketika berbicara, kecenderungan gaya bicara saya...' ,
                'id_option_a' => 1,
                'option_a' => 'Cepat',
                'id_option_b' => 2,
                'option_b' => 'Berirama',
                'id_option_c' => 3,
                'option_c' => 'Lambat',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK30',
                'question_text' => 'Saya...' ,
                'id_option_a' => 1,
                'option_a' => 'Mampu merencanakan dan mengatur kegiatan jangka panjang dengan baik',
                'id_option_b' => 2,
                'option_b' => 'Mampu mengulang dan menirukan nada, perubahan, dan warna suara',
                'id_option_c' => 3,
                'option_c' => 'Mahir dalam mengerjakan puzzle, teka-teki, menyusun potongan-potongan Gambar',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK31',
                'question_text' => '3.	Saya dapat mengingat dengan baik informasi yang...' ,
                'id_option_a' => 1,
                'option_a' => 'Tertulis di papan tulis atau yang diberikan melalui tugas membaca',
                'id_option_b' => 2,
                'option_b' => 'Disampaikan melalui penjelasan guru, diskusi, atau rekaman',
                'id_option_c' => 3,
                'option_c' => 'Diberikan dengan cara menuliskannya berkali-kali',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK32',
                'question_text' => 'Saya menghafal sesuatu...' ,
                'id_option_a' => 1,
                'option_a' => 'Dengan membayangkannya',
                'id_option_b' => 2,
                'option_b' => 'Dengan mengucapkannya dengan suara yang keras',
                'id_option_c' => 3,
                'option_c' => 'Sambil berjalan dan melihat-lihat keadaan sekeliling',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK33',
                'question_text' => 'Saya merasa sulit...' ,
                'id_option_a' => 1,
                'option_a' => 'Mengingat perintah lisan kecuali jika dituliskan',
                'id_option_b' => 2,
                'option_b' => 'Menulis tetapi pandai bercerita',
                'id_option_c' => 3,
                'option_c' => 'Duduk tenang untuk waktu yang lama',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK34',
                'question_text' => 'Saya lebih suka...' ,
                'id_option_a' => 1,
                'option_a' => 'Membaca daripada dibacakan',
                'id_option_b' => 2,
                'option_b' => 'Mendengar daripada membaca',
                'id_option_c' => 3,
                'option_c' => 'Menggunakan model dan praktek atau praktikum',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK35',
                'question_text' => 'Saya suka...' ,
                'id_option_a' => 1,
                'option_a' => 'Mencoret-coret selama menelepon, mendengarkan musik, atau menghadiri rapat',
                'id_option_b' => 2,
                'option_b' => 'Membaca keras-keras dan mendengarkan musik/pembicaraan',
                'id_option_c' => 3,
                'option_c' => 'Mengetuk-ngetuk pena, jari, atau kaki saat mendengarkan musik/pembicaraan',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK36',
                'question_text' => 'Saya lebih suka melakukan...' ,
                'id_option_a' => 1,
                'option_a' => 'Demonstrasi daripada berpidato',
                'id_option_b' => 2,
                'option_b' => 'Diskusi dan berbicara panjang lebar',
                'id_option_c' => 3,
                'option_c' => 'Berolahraga dan kegiatan fisik lainnya',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK37',
                'question_text' => 'Saya lebih menyukai...' ,
                'id_option_a' => 1,
                'option_a' => 'Seni rupa daripada musik',
                'id_option_b' => 2,
                'option_b' => 'Musik daripada seni rupa',
                'id_option_c' => 3,
                'option_c' => 'Olahraga dan kegiatan fisik lainnya',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK38',
                'question_text' => 'Ketika mengerjakan sesuatu, saya selalu...' ,
                'id_option_a' => 1,
                'option_a' => 'Mengikuti petunjuk dan gambar yang disediakan',
                'id_option_b' => 2,
                'option_b' => 'Membicarakan dengan orang lain atau berbicara sendiri keras-keras',
                'id_option_c' => 3,
                'option_c' => 'Mencari tahu cara kerjanya sambil mengerjakannya',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK39',
                'question_text' => 'Konsentrasi saya terganggu oleh...' ,
                'id_option_a' => 1,
                'option_a' => 'Ketidakteraturan atau gerakan',
                'id_option_b' => 2,
                'option_b' => 'suara atau keributan',
                'id_option_c' => 3,
                'option_c' => 'Kegiatan di sekeliling',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK40',
                'question_text' => 'Saya lebih mudah belajar melalui kegiatan...' ,
                'id_option_a' => 1,
                'option_a' => 'Membaca',
                'id_option_b' => 2,
                'option_b' => 'Mendengarkan dan berdiskusi',
                'id_option_c' => 3,
                'option_c' => 'Praktek atau praktikum',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK41',
                'question_text' => 'Saya berbicara dengan...' ,
                'id_option_a' => 1,
                'option_a' => 'Singkat dan tidak senang mendengarkan pembicaraan panjang',
                'id_option_b' => 2,
                'option_b' => 'Cepat dan senang mendengarkan',
                'id_option_c' => 3,
                'option_c' => 'Menggunakan isyarat tubuh dan gerakan-gerakan ekspresif',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK42',
                'question_text' => 'Untuk mengetahui suasana hati seseorang, saya …' ,
                'id_option_a' => 1,
                'option_a' => 'Melihat ekspresi wajahnya',
                'id_option_b' => 2,
                'option_b' => 'Mendengarkan nada suara',
                'id_option_c' => 3,
                'option_c' => 'Memperhatikan gerakan badannya',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK43',
                'question_text' => 'Untuk mengisi waktu luang, saya lebih suka ...' ,
                'id_option_a' => 1,
                'option_a' => 'Menonton televisi atau menyaksikan pertunjukan',
                'id_option_b' => 2,
                'option_b' => 'Mendengarkan radio, musik, atau membaca',
                'id_option_c' => 3,
                'option_c' => 'Melakukan permainan atau bekerja dengan menggunakan tangan',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_soal' => 'ADNK44',
                'question_text' => 'Ketika mengajarkan sesuatu kepada orang lain, saya lebih suka ...' ,
                'id_option_a' => 1,
                'option_a' => 'Menunjukkannya',
                'id_option_b' => 2,
                'option_b' => 'Menceritakannya',
                'id_option_c' => 3,
                'option_c' => 'Mendemonstrasikannya dan meminta mereka untuk mencobanya',
                'category' => 'C',
                'created_at' => now(),
                'updated_at' => now()
            ],

        ];
        // Menyimpan data ke dalam tabel questions
        DB::table('questions')->insert($questions);
    }
}
